version: "3.9"

services:
    go:
        container_name: go
        image: go
        restart: on-failure
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        depends_on:
            - db
        environment:
            SECRET: ?M/Xnn8#H).W96T[
        ports:
            - "8080:8080"
        expose:
            - 8080
        # networks:
        #     - elastic
    db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_DATABASE: Blobber
        MYSQL_USER: bano
        MYSQL_PASSWORD: bano
        MYSQL_ROOT_PASSWORD: root
      ports:
        - 33061:3306
      # expose:
      #   - 3306
      volumes:
        - my-db:/var/lib/mysql
volumes:
  my-db:
# networks:
#   elastic:
#     driver: bridge