version: "3.9"

services:
    go:
        container_name: go
        image: go
        restart: on-failure
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        depends_on:
            - db
        environment:
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
        ports:
            - "${PORT}:8080"
        # networks:
        #     - elastic
    db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_DATABASE: Blobber
        MYSQL_USER: vano
        MYSQL_PASSWORD: vano
        MYSQL_ROOT_PASSWORD: root
      ports:
        - 33061:3306
      expose:
        - 3306
      volumes:
        - my-db:/var/lib/mysql

# networks:
#   elastic:
#     driver: bridge