version: "3.3"
services:
  db:
      image: mariadb:10.2
      restart: always
      environment:
        MYSQL_DATABASE: blobber
        MYSQL_USER: vano
        MYSQL_PASSWORD: vano
        MYSQL_ROOT_PASSWORD: root
      ports:
        - "3306:3306"
      expose:
        - 3306
      volumes:
        - ./db-dump:/var/lib/mysql
volumes: 
  mariadb:
