version: "3.3"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: Blobber
      MYSQL_USER: vano
      MYSQL_PASSWORD: vano
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 33061:3306
    expose:
      - 3306
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
