CREATE TABLE blobber.blobs (
	ID INT auto_increment NOT NULL,
	ID_user INT NOT NULL,
	content MEDIUMTEXT NULL,
	added_date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY(ID),
);
-- ENGINE=InnoDB
-- DEFAULT CHARSET=utf8mb4
-- COLLATE=utf8mb4_unicode_ci;
